name: CI

on:
  push:
    branches:
      - source

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Get env info
        run: env && pwd
      - name: Pelican for GitHub Pages
        uses: nelsonjchen/gh-pages-pelican-action@0.1.4
